;
; M32ASSEM_SERIALIZING_DATA_OUT.asm
;
; Created: 21-Nov-17 08:41:57 PM
; Author : Mahmoud
;

		.ORG 0X00
		LDI R16,HIGH(RAMEND)
		OUT SPH,R16
		LDI R16,LOW(RAMEND)
		OUT SPL,R16
		;LDI R16,0B11001010
		;CLC
	  
MAIN  :					
		SBI DDRB,1		;SET THE BIT AS AN OUTPUT
		LDI R16,8		;WILL NEED TO LOOP 8 TIMES DUE TO THE SIZE OF THE REGISTER WE WORKS BY
		LDI R17,0X86	;DATA WIL BE SENT
		CLC				;CLEAR THE CARRY

		;SBI PORTB,1		;A STARTING HIGH BIT 

LOOP  :	
		ROR R17			;ROTATE RIGHT THROUGH THE CARRY SO CAN TAKE DECISIONS BASED ON C
		BRCS HIBIT		;IF C IS NOW HIGH GOTO THE HIBIT LABLE
		CBI	PORTB,1		;ELSE C IS LOW SO CLEAR THE BIT             "SET IT TO ZERO"
		RJMP CONT		;GOTO CONTINUE LABLE						|
HIBIT :	SBI PORTB,1		;HERE CAME AS C IS HIGH SO WILL SET THE BIT "SET IT TO ONE"
		
CONT  :	DEC R16			;DECREMENT THE COUNTER
		BRNE LOOP		;REPEAT EAIGHT TIMES

		;SBI PORTB,1		;AN ENDING HIGH BIT

HERE : 	RJMP HERE
